// src/use-cases/places/CreatePlace.ts
import { Place } from "../../domain/entities/Place";
import { PlaceRepository } from "../../domain/interfaces/placeRepository";
import { CreatePlaceDto } from "../../interface/dto/CreatePlaceDto";

export class CreatePlace {
  constructor(private readonly placeRepository: PlaceRepository) {}

  async execute(placeData: CreatePlaceDto): Promise<Place> {
    const place = new Place(
      "", // ID will be generated by repository
      placeData.type,
      placeData.name,
      { x: placeData.longitude, y: placeData.latitude }, // Convert to PostGIS point
      placeData.address,
      placeData.details || {},
      new Date(), // created_at
      undefined // updated_at
    );

    return await this.placeRepository.create(place);
  }
}